# Generated by Django 3.1.5 on 2021-01-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='sorceUrl',
            new_name='sourceUrl',
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
