export const ONLOAD_SEARCH = 'SEARCH_ONLOAD';

export const SUCCESS_SEARCH = 'SEARCH_SUCCESS';

export const NULL_SEARCH = 'SEARCH_NULL';

export const NOT_RESULT_SEARCH = 'SEARCH_NOT_RESULT';

export const SET_PARAMS_SEARCH = 'SET_PARAMS_SEARCH';

export const OPEN_MODAL_FORM = 'OPEN_MODAL_FORM';

export const CLOSE_MODAL_OPEN = 'CLOSE_MODAL_OPEN';

export const SET_STATE_MODAL_FORM = 'SET_STATE_MODAL_FORM';

export const SUBMIT_FORM_EDIT_ARTICLE = 'SUBMIT_FORM_EDIT_ARTICLE';

export const OPEN_MODAL_ERROR = 'OPEN_MODAL_ERROR';

export const CLOSE_MODAL_ERROR = 'CLOSE_MODAL_ERROR';

